# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonproje\StajTakip\frm_ogretmenGiris.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from ogretmenEkrani import OgretmenEkrani_MainWindow

from tkinter import messagebox
import sys
import sqlite3
global curs
global conn

conn=sqlite3.connect('stjyrtkp.sqlite')
curs=conn.cursor()
global mesaj





class OgrtGiris_MainWindow(object):
    

    def Kaydol(self):
        from Frm_OgrtKayit import OgrtKayit_Window
        self.window = QtWidgets.QMainWindow()
        self.ui2 = OgrtKayit_Window()
        self.ui2.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(317, 265)
        MainWindow.setStyleSheet(".QWidget {\n"
"   background-color: beige;\n"
"}\n"
"\n"
"/* Nice Windows-XP-style password character. */\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"\n"
"/* We provide a min-width and min-height for push buttons\n"
"   so that they look elegant regardless of the width of the text. */\n"
"QPushButton {\n"
"    background-color: palegoldenrod;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: khaki;\n"
"}\n"
"\n"
"/* Increase the padding, so the text is shifted when the button is\n"
"   pressed. */\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #d0d67c;\n"
"}\n"
"\n"
"QLabel, QAbstractButton {\n"
"    font: bold;\n"
"}\n"
"\n"
"/* Mark mandatory fields with a brownish color. */\n"
".mandatory {\n"
"    color: brown;\n"
"}\n"
"\n"
"/* Bold text on status bar looks awful. */\n"
"QStatusBar QLabel {\n"
"   font: normal;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border-width: 1;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QComboBox, QLineEdit, QSpinBox, QTextEdit, QListView {\n"
"    background-color: cornsilk;\n"
"    selection-color: #0a214c; \n"
"    selection-background-color: #C19A6B;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QListView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* We reserve 1 pixel space in padding. When we get the focus,\n"
"   we kill the padding and enlarge the border. This makes the items\n"
"   glow. */\n"
"QLineEdit, QFrame {\n"
"    border-width: 2px;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border-color: darkkhaki;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* As mentioned above, eliminate the padding and increase the border. */\n"
"QLineEdit:focus, QFrame:focus {\n"
"    border-width: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* A QLabel is a QFrame ... */\n"
"QLabel {\n"
"    border: none;\n"
"    padding: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"/* A QToolTip is a QLabel ... */\n"
"QToolTip {\n"
"    border: 2px solid darkkhaki;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"/* Nice to have the background color change when hovered. */\n"
"QRadioButton:hover, QCheckBox:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* Force the dialog\'s buttons to follow the Windows guidelines. */\n"
"QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: palegoldenrod(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"   border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: palegoldenrod;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-bottom-color: #darkkhaki; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: khaki;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    \n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblKullaniciAdi = QtWidgets.QLabel(self.centralwidget)
        self.lblKullaniciAdi.setGeometry(QtCore.QRect(10, 70, 121, 31))
        self.lblKullaniciAdi.setObjectName("lblKullaniciAdi")
        self.lineKullaniciAdi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineKullaniciAdi.setGeometry(QtCore.QRect(140, 70, 171, 31))
        self.lineKullaniciAdi.setObjectName("lineKullaniciAdi")
        self.lineKullaniciAdi.setMaxLength(11)
        
        self.lineSifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSifre.setGeometry(QtCore.QRect(140, 110, 171, 31))
        self.lineSifre.setText("")
        self.lineSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineSifre.setClearButtonEnabled(False)
        self.lineSifre.setObjectName("lineSifre")
        self.lineSifre.setMaxLength(11)
        self.lblSifre = QtWidgets.QLabel(self.centralwidget)
        self.lblSifre.setGeometry(QtCore.QRect(10, 110, 121, 31))
        self.lblSifre.setObjectName("lblSifre")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnGiris = QtWidgets.QPushButton(self.centralwidget)
        self.btnGiris.setGeometry(QtCore.QRect(10, 150, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnGiris.setFont(font)
        self.btnGiris.setObjectName("btnGiris")
        self.btnKapat = QtWidgets.QPushButton(self.centralwidget)
        self.btnKapat.setGeometry(QtCore.QRect(260, 10, 51, 51))
        self.btnKapat.setObjectName("btnKapat")
        self.btnKayt = QtWidgets.QPushButton(self.centralwidget)
        self.btnKayt.setGeometry(QtCore.QRect(10, 190, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnKayt.setFont(font)
        self.btnKayt.setObjectName("btnKayt")
        self.btnUnuttum = QtWidgets.QPushButton(self.centralwidget)
        self.btnUnuttum.setGeometry(QtCore.QRect(10, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnUnuttum.setFont(font)
        self.btnUnuttum.setObjectName("btnUnuttum")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnGiris.clicked.connect(self.GETIR)
        self.btnKayt.clicked.connect(self.Kaydol)
    
       
        

    def GETIR(self):
        global mesaj
        _ogrTCno=self.lineKullaniciAdi.text()   
        _ogrSifre=self.lineSifre.text()
        mesaj=" "
        curs.execute("SELECT * FROM ogretmen WHERE ogretmen_tcno = ? AND ogretmen_Sifre =?",(_ogrTCno,_ogrSifre))
        veriler=curs.fetchone()
        if veriler:
            app = QtWidgets.QApplication(sys.argv)
            MainWindow = QtWidgets.QMainWindow()
            self.ui = OgretmenEkrani_MainWindow()
            self.ui.setupUi(MainWindow)
            MainWindow.show()
        else:
            messagebox.showinfo("Hata", "Kullanıcı bulunamadı / Hatalı giriş")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Öğretmen Girişi"))
        self.lblKullaniciAdi.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.lblSifre.setText(_translate("MainWindow", "Şifre: "))
        self.label.setText(_translate("MainWindow", "Öğretmen Giriş"))
        self.btnGiris.setText(_translate("MainWindow", "Giriş"))
        self.btnKapat.setText(_translate("MainWindow", "X"))
        self.btnKayt.setText(_translate("MainWindow", "Kayıt Ol"))
        self.btnUnuttum.setText(_translate("MainWindow", "Şifremi Unuttum"))
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form= QtWidgets.QMainWindow()
    ui = OgrtGiris_MainWindow()
    ui.setupUi(MainWindow)
    Form.show()
    sys.exit(app.exec_())
