# -*- coding: utf-8 -*-

# Form implementation generated from reading self file 'D:\pythonproje\StajTakip\OgretmenGirisIslemleri.self'
#
# Created by: PyQt5 self code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyselfc5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from tkinter import messagebox
import sys
import sqlite3
global curs
global conn

conn=sqlite3.connect('stjyrtkp.sqlite')
curs=conn.cursor()
global mesaj

class OgrtKayit_Window(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(431, 269)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btnKaydet = QtWidgets.QPushButton(dialog)
        self.btnKaydet.setGeometry(QtCore.QRect(190, 230, 75, 23))
        self.btnKaydet.setObjectName("btnKaydet")
        self.btnGuncelle = QtWidgets.QPushButton(dialog)
        self.btnGuncelle.setGeometry(QtCore.QRect(270, 230, 75, 23))
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.btnSil = QtWidgets.QPushButton(dialog)
        self.btnSil.setGeometry(QtCore.QRect(350, 230, 75, 23))
        self.btnSil.setObjectName("btnSil")
        self.btnKytGetir = QtWidgets.QPushButton(dialog)
        self.btnKytGetir.setGeometry(QtCore.QRect(110, 230, 75, 23))
        self.btnKytGetir.setObjectName("btnKytGetir")
        self.btnTemizle = QtWidgets.QPushButton(dialog)
        self.btnTemizle.setGeometry(QtCore.QRect(30, 230, 75, 23))
        self.btnTemizle.setObjectName("btnTemizle")
        self.txtTcno = QtWidgets.QLineEdit(dialog)
        self.txtTcno.setGeometry(QtCore.QRect(190, 20, 231, 31))
        self.txtTcno.setText("")
        self.txtTcno.setObjectName("txtTcno")
        self.txtSifre = QtWidgets.QLineEdit(dialog)
        self.txtSifre.setGeometry(QtCore.QRect(190, 60, 231, 31))
        self.txtSifre.setText("")
        self.txtSifre.setObjectName("txtSifre")
        self.txtAdSoyad = QtWidgets.QLineEdit(dialog)
        self.txtAdSoyad.setGeometry(QtCore.QRect(190, 100, 231, 31))
        self.txtAdSoyad.setText("")
        self.txtAdSoyad.setObjectName("txtAdSoyad")
        self.txtBrans = QtWidgets.QLineEdit(dialog)
        self.txtBrans.setGeometry(QtCore.QRect(190, 140, 231, 31))
        self.txtBrans.setText("")
        self.txtBrans.setObjectName("txtBrans")
        self.txtMail = QtWidgets.QLineEdit(dialog)
        self.txtMail.setGeometry(QtCore.QRect(190, 180, 231, 31))
        self.txtMail.setText("")
        self.txtMail.setObjectName("txtMail")

        self.retranslateself(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        self.btnTemizle.clicked.connect(self.TEMIZLE)
        self.btnKaydet.clicked.connect(self.EKLE)
        self.btnGuncelle.clicked.connect(self.GUNCELLE)
        self.btnKytGetir.clicked.connect(self.GETIR)
        self.btnSil.clicked.connect(self.SIL)
        self.txtSifre.setMaxLength(11)
        self.txtTcno.setMaxLength(11)
        self.btnGuncelle.setEnabled(False)
        self.btnSil.setEnabled(False)

    def retranslateself(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Öğretmen Kayıt İşlemleri"))
        self.label.setText(_translate("dialog", "Tc No"))
        self.label_2.setText(_translate("dialog", "Ad Soyad"))
        self.label_3.setText(_translate("dialog", "Şifre"))
        self.label_4.setText(_translate("dialog", "Branş"))
        self.label_5.setText(_translate("dialog", "E-Posta"))
        self.btnKaydet.setText(_translate("dialog", "Kaydet"))
        self.btnGuncelle.setText(_translate("dialog", "Güncelle"))
        self.btnSil.setText(_translate("dialog", "Sil"))
        self.btnKytGetir.setText(_translate("dialog", "Kayıt Getir"))
        self.btnTemizle.setText(_translate("dialog", "Temizle"))

    def TEMIZLE(self):
        self.txtTcno.clear()
        self.txtBrans.clear()
        self.txtMail.clear()
        self.txtSifre.clear()
        self.txtAdSoyad.clear()
        self.txtTcno.setEnabled(True)
        self.btnGuncelle.setEnabled(False)
        self.btnSil.setEnabled(False)
        
    def GirisKontrol(self):
        _ogrTCno=self.txtTcno.text()
        _ogrAdiSoyadi=self.txtAdSoyad.text()
        _ogrSifre=self.txtSifre.text()
        _ogrBrans=self.txtBrans.text()
        _ogrMail=self.txtMail.text()
        global mesaj
        deger=True
        if len(_ogrTCno)!=11 or _ogrTCno.isdigit()==False or int(_ogrTCno[0])==0:
            mesaj+="Tc No "
            deger=False
        if _ogrAdiSoyadi.isdigit==True or len(_ogrAdiSoyadi)<2:
            mesaj+="Adı Soyadı "
            deger=False
        if len(_ogrSifre)<6:
            mesaj+="Sifre "
            deger=False
        if len(_ogrBrans)<3:
            mesaj+="Branş "
            deger=False
        if len(_ogrMail)<5 or _ogrMail.find('@')==-1:
            mesaj+="Mail"
            deger=False
        return deger

    def EKLE(self):  
        global mesaj
        _ogrTCno=self.txtTcno.text()
        _ogrAdiSoyadi=self.txtAdSoyad.text()
        _ogrSifre=self.txtSifre.text()
        _ogrBrans=self.txtBrans.text()
        _ogrMail=self.txtMail.text()
        mesaj=" "
        if len(_ogrTCno)!=11 or _ogrTCno.isdigit()==False or int(_ogrTCno[0])==0:
           messagebox.showinfo("Hata", "Girişleri kontrol ediniz:")
        else:
            curs.execute("SELECT * FROM ogretmen WHERE ogretmen_tcno = %s"%(_ogrTCno))
            veriler=curs.fetchone()
            if veriler:    
                messagebox.showinfo("Hata", "Kayıtlı bir TC Numarası girdiniz.")
            else:
                if self.GirisKontrol()==False:
                    messagebox.showinfo("Hata", "Girişleri kontrol ediniz:" + mesaj)
                else:
                    curs.execute("INSERT INTO ogretmen \
                         (ogretmen_tcno,ogretmen_AdSoyad,ogretmen_Sifre,ogretmen_Alan,ogretmen_email) \
                         VALUES (?,?,?,?,?)", \
                         (_ogrTCno,_ogrAdiSoyadi,_ogrSifre,_ogrBrans,_ogrMail))
                    conn.commit()         
                    self.TEMIZLE()
                    messagebox.showinfo("Kayıt İşlemi", "Kayıt işlemi gerçekleşti.")

    def GETIR(self):
        global mesaj
        _ogrTCno=self.txtTcno.text()   
        _ogrSifre=self.txtSifre.text()
        mesaj=" "
        curs.execute("SELECT * FROM ogretmen WHERE ogretmen_tcno = ? AND ogretmen_Sifre =?",(_ogrTCno,_ogrSifre))
        veriler=curs.fetchone()
        if veriler:
            self.txtAdSoyad.setText(veriler[1])
            self.txtBrans.setText(veriler[3])
            self.txtMail.setText(veriler[4])
            self.btnGuncelle.setEnabled(1)
            self.txtTcno.setEnabled(False)
            self.btnGuncelle.setEnabled(True)
            self.btnSil.setEnabled(True)
        else:
            messagebox.showinfo("Hata", "Kullanıcı bulunamadı / Hatalı giriş")
            self.btnGuncelle.setEnabled(False)
            self.btnSil.setEnabled(False)
                 
    
    def GUNCELLE(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setText("Kaydı güncellemek istiyor musunuz?")
        msg.setWindowTitle("Güncelleme")
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        cevap=msg.exec()
        if cevap==QMessageBox.Yes:
            try:
                _ogrTCno=self.txtTcno.text()
                _ogrAdiSoyadi=self.txtAdSoyad.text()
                _ogrSifre=self.txtSifre.text()
                _ogrBrans=self.txtBrans.text()
                _ogrMail=self.txtMail.text()
                curs.execute("UPDATE ogretmen SET ogretmen_AdSoyad=?, ogretmen_Sifre=?, ogretmen_Alan=?, ogretmen_email=? WHERE ogretmen_tcno=?", (_ogrAdiSoyadi,_ogrSifre,_ogrBrans,_ogrMail,_ogrTCno))
                conn.commit()
                messagebox.showinfo("Güncelleme", "Kayıt Güncelleme Başarılı")
                self.TEMIZLE()
            except Exception as Hata:
                messagebox.showinfo("Hata", str(Hata))
            
        else:
            messagebox.showinfo("Hata", "Güncellme iptal edildi")

    def SIL(self):
        msg1 = QMessageBox()
        msg1.setIcon(QMessageBox.Question)
        msg1.setText("Kaydı silmek istiyor musunuz?")
        msg1.setWindowTitle("Silme İşlemi")
        msg1.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        cevap1=msg1.exec()
        if cevap1==QMessageBox.Yes:
            tcno=self.txtTcno.text()
            try:
                curs.execute("DELETE FROM ogretmen WHERE ogretmen_tcno='%s'" %(tcno))
                conn.commit()
                self.TEMIZLE()      
                messagebox.showinfo("Silme İşlemi","Kayıt silindi")
            except Exception as Hata:
                messagebox.showinfo("Hata", str(Hata))
           
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form= QtWidgets.QMainWindow()
    ui = OgrtKayit_Window()
    ui.setupUi(dialog)
    Form.show()
    sys.exit(app.exec_())