# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonproje\StajTakip\frm_anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ana_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 121)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: palegoldenrod;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"    font: 75 12pt \"Arial\";\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"   background-color: khaki;\n"
"}\n"
"\n"
".QWidget {\n"
"    background-color:beige;\n"
"    font: 75 12pt \"Arial\";\n"
"\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: khaki;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnOgretmen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOgretmen.setGeometry(QtCore.QRect(10, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnOgretmen.setFont(font)
        self.btnOgretmen.setStyleSheet("\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnOgretmen.setObjectName("btnOgretmen")
        self.btnFirma = QtWidgets.QPushButton(self.centralwidget)
        self.btnFirma.setGeometry(QtCore.QRect(150, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnFirma.setFont(font)
        self.btnFirma.setObjectName("btnFirma")
        self.btnOgrenci = QtWidgets.QPushButton(self.centralwidget)
        self.btnOgrenci.setGeometry(QtCore.QRect(290, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnOgrenci.setFont(font)
        self.btnOgrenci.setObjectName("btnOgrenci")
        self.btnKapat = QtWidgets.QPushButton(self.centralwidget)
        self.btnKapat.setGeometry(QtCore.QRect(350, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnKapat.setFont(font)
        self.btnKapat.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnKapat.setObjectName("btnKapat")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btnOgretmen.clicked.connect(self.ogretmenAc)

    def ogretmenAc(self):
        from frm_ogrtGiris import OgrtGiris_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = OgrtGiris_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.setVisible(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Staj Takip"))
        self.label.setText(_translate("MainWindow", "STAJ TAKİP - NohtyP"))
        self.btnOgretmen.setText(_translate("MainWindow", "Öğretmen Girişi"))
        self.btnFirma.setText(_translate("MainWindow", "Firma Girişi"))
        self.btnOgrenci.setText(_translate("MainWindow", "Öğrenci Girişi"))
        self.btnKapat.setText(_translate("MainWindow", "Kapat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ana_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    sys.exit(app.exec_())
